### ISSUE TITLE
 ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by xxnjdlys** [android-async-http/android-async-http#1035]
I keep getting this issue below after updating to 1.4.9 , android sdk 23 in some device like Nexus5(android 6.0)。 but 1.4.6 works fine for me . how can I fix this issue? Thanks in advance.

here is how I use it .

``` java
public void post(Context context, String url, HttpEntity entity, String contentType, ResponseHandlerInterface responseHandler) {
        checkInitialized();
        mAsyncHttpClient.post(context, url, entity, contentType, responseHandler);
    }
```

```
java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 12580) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
     at libcore.io.IoBridge.isConnected(IoBridge.java:238)
     at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
     at libcore.io.IoBridge.connect(IoBridge.java:122)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
     at java.net.Socket.connect(Socket.java:882)
     at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
     at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED 
```

**Comment by zhangxy1219** [comment]
This seems to be the same issue with https://github.com/loopj/android-async-http/issues/990

**Comment by hardslk** [comment]
This seems to be the same issue with remote ip address

**Comment by smarek** [comment]
Unless you can provide server, where the issue can be reproduced, I'm unable to provide any support.
Feel free to reopen with more debug info. Thank you
