### ISSUE TITLE
There are something wrong in version 1.4.9

### ISSUE THREAD

**Issue by wangxuguo** [android-async-http/android-async-http#1084]
When I used version 1.4.9,Sometimes,the request does not get successful!
Some log are followd:
```
01-19 14:36:38.355: W/System.err(13825): cz.msebera.android.httpclient.conn.ConnectTimeoutException: Connect to /113.59.227.10:82 timed out
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
01-19 14:36:38.360: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
01-19 14:36:38.360: W/System.err(13825):    at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
01-19 14:36:38.360: W/System.err(13825):    at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
01-19 14:36:38.360: W/System.err(13825):    at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
01-19 14:36:38.360: W/System.err(13825):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-19 14:36:38.360: W/System.err(13825):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-19 14:36:38.360: W/System.err(13825):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-19 14:36:38.365: W/System.err(13825):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-19 14:36:38.365: W/System.err(13825):    at java.lang.Thread.run(Thread.java:841)
01-19 14:36:38.365: W/System.err(13825): cz.msebera.android.httpclient.conn.ConnectTimeoutException: Connect to /113.59.227.10:82 timed out
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
01-19 14:36:38.365: W/System.err(13825):    at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
01-19 14:36:38.365: W/System.err(13825):    at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
01-19 14:36:38.370: W/System.err(13825):    at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
01-19 14:36:38.370: W/System.err(13825):    at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
01-19 14:36:38.370: W/System.err(13825):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-19 14:36:38.370: W/System.err(13825):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-19 14:36:38.370: W/System.err(13825):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-19 14:36:38.370: W/System.err(13825):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-19 14:36:38.370: W/System.err(13825):    at java.lang.Thread.run(Thread.java:841)
01-19 14:36:38.370: E/SettingSportGoalActivity_(13825): OnFailure:http://113.59.227.10:82/dcare/api/web/index.php?r=user/edit&access_token=9a80053c1bf5887b4150d63fb1836362 statusCode0
```
Is anyone else found this problem?

**Comment by wwiilla** [comment]
You solve this problem ?

**Comment by lkishor** [comment]
this problem occurs with me as well, when you try to use a static AsyncHttpClient object to make more than one request after some time gap.
Though this is usage pattern on the documentation, it is the source of this error.

To avoid this you may have to create new AsyncHttpClient object for every web service request.
`public static AsyncHttpClient getClient() {
        AsyncHttpClient client = new AsyncHttpClient();
        client.setTimeout(20000);
        client.setMaxRetriesAndTimeout(1, 5000);
        return client;
    }`
and use it as `getClient().get(Context, URL, RequestParams, Callback)`

**Comment by andymiao** [comment]
How to solve this problem？

**Comment by vinod1988** [comment]
Is there any way to solve this issue. Because its very critical for my app.

**Comment by smarek** [comment]
Well connect-timeout is self-descriptive, you should raise timeouts as per @lkishor comment, or fix your backend if possible.
Such issues, unless you've got any hint it's issue of library, should be discussed on stackoverflow.com
