### ISSUE TITLE
Cannot close input stream over HTTPS connection.

### ISSUE THREAD

**Issue by virag-audetemi** [android-async-http/android-async-http#1173]
I have integrated the SSL certificate, and configured the same with AsyncHttpClient.

`public class CustomSSLSocketFactory {

```
private final String TAG = "CustomSSLSocketFactory";

public SSLSocketFactory getSSLSocketFactory(Context context) {
    SSLSocketFactory sslSocketFactory = null;
    try {
        final KeyStore ks = KeyStore.getInstance("BKS");
        final InputStream inputStream = context.getResources().openRawResource(R.raw.my_certificate);
        ks.load(inputStream, context.getString(R.string.ssl_password).toCharArray());
        sslSocketFactory = new SSLSocketFactory(ks);
        inputStream.close();
    } catch (UnrecoverableKeyException ex) {
        Log.d(TAG, ex.getMessage());
    } catch (KeyStoreException ex) {
        Log.d(TAG, ex.getMessage());
    } catch (KeyManagementException ex) {
        Log.d(TAG, ex.getMessage());
    } catch (NoSuchAlgorithmException ex) {
        Log.d(TAG, ex.getMessage());
    } catch (IOException ex) {
        Log.d(TAG, ex.getMessage());
    } catch (Exception ex) {
        Log.d(TAG, ex.getMessage());
    }
    return sslSocketFactory;
}
```

}`

Using              `asyncHttpClient.setSSLSocketFactory(customSSLSocketFactory.getSSLSocketFactory(context));
`

Getting following exception in the stack trace, also this results into failing some web services:
```
Cannot close input stream
                                                                            java.net.SocketException: Socket is closed
                                                                                at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:238)
                                                                                at com.android.org.conscrypt.OpenSSLSocketImpl.access$100(OpenSSLSocketImpl.java:63)
                                                                                at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:685)
                                                                                at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
                                                                                at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
                                                                                at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
                                                                                at cz.msebera.android.httpclient.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:228)
                                                                                at cz.msebera.android.httpclient.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:206)
                                                                                at cz.msebera.android.httpclient.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:169)
                                                                                at cz.msebera.android.httpclient.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:198)
                                                                                at cz.msebera.android.httpclient.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:287)
                                                                                at com.loopj.android.http.AsyncHttpClient.silentCloseInputStream(AsyncHttpClient.java:397)
                                                                                at com.loopj.android.http.AsyncHttpClient$InflatingEntity.consumeContent(AsyncHttpClient.java:1631)
                                                                                at com.loopj.android.http.AsyncHttpClient.endEntityViaReflection(AsyncHttpClient.java:440)
                                                                                at com.loopj.android.http.AsyncHttpResponseHandler.getResponseData(AsyncHttpResponseHandler.java:485)
                                                                                at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:442)
                                                                                at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:160)
                                                                                at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
                                                                                at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)
```

**Comment by virag-audetemi** [comment]
Any updates on this??

**Comment by smarek** [comment]
Well socket is closed, so is the input stream, and the stacktrace you've posted originates in `AsyncHttpClient.silentCloseInputStream` which closes the stream silently (without throwing error/exception), but logs such exception for dev purposes.

I don't see any error per-se that I could address
