### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Handshake failed when download from HTTPS

### ISSUE THREAD

**Issue by bigant88** [android-async-http/android-async-http#1178]
I tried to download this link: https://images.where.place/walkpaths/B1%20%281%29.svg
But error happened: 

06-30 03:33:44.588 1207-1207/com.loopj.android.http.sample E/FileSample: AsyncHttpClient returned error
                                                                         javax.net.ssl.SSLHandshakeException: Handshake failed
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
                                                                             at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
                                                                             at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
                                                                             at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
                                                                             at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
                                                                             at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
                                                                             at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
                                                                             at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
                                                                             at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
                                                                             at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
                                                                             at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
                                                                             at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
                                                                             at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
                                                                             at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
                                                                             at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x70739800: Failure in SSL library, usually a protocol error
                                                                         error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:765 0x6cdaa098:0x00000000)
                                                                             at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
                                                                                ... 19 more

**Comment by ending0421** [comment]
What is your OS version? 6.0? if true , seems server ssl encrypt key length less than 1024 . See https://groups.google.com/forum/#!topic/android-developers/1Hp9kHSli-g

**Comment by smarek** [comment]
Thanks, this will be solved in #1029, where I'll concentrace issues about using new underlying HttpClient library and cross-support of SSL/TLS versions vs. Server supported versions
