### ISSUE TITLE
 java.io.IOException: NPE in HttpClient:Attempt to invoke virtual method 'void java.net.Socket.setTcpNoDelay(boolean)' on a null object reference

### ISSUE THREAD

**Issue by vyshas** [android-async-http/android-async-http#1192]
Issue happens only when  asynClient.setSSLSocketFactory(factory) is used .        

```
08-08 11:08:41.195: W/System.err(7952): java.io.IOException: NPE in HttpClient: Attempt to invoke virtual method 'void java.net.Socket.setTcpNoDelay(boolean)' on a null object reference
08-08 11:08:41.196: W/System.err(7952):     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:189)
08-08 11:08:41.196: W/System.err(7952):     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
08-08 11:08:41.196: W/System.err(7952):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
08-08 11:08:41.196: W/System.err(7952):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-08 11:08:41.196: W/System.err(7952):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-08 11:08:41.196: W/System.err(7952):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-08 11:08:41.196: W/System.err(7952):     at java.lang.Thread.run(Thread.java:818)
```

``````
/**
     * 
     * @param enableSSL enableSSL value from config
     * @return loopj AsyncHttpClient and sets SSLsocketfactory based on enableSSL value
     */
    public static AsyncHttpClient getAsynHttpClient(int enableSSL)
    {
        AsyncHttpClient asynClient=  new AsyncHttpClient();
        if(enableSSL<=0) return asynClient;
        try {
            KeyStore  trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
            trustStore.load(null, null);
            SSLSocketFactoryApache factory = new SSLSocketFactoryApache(trustStore);
            asynClient.setSSLSocketFactory(factory);
            return asynClient;
        } catch (Exception e1) {
            e1.printStackTrace();
            return null;
        }

```asynClient=getAsynHttpClient(enableSSL)
      asynClient.addHeader("Content-Type","application/json");
                asynClient.setUserAgent("CIQUALBOT");
                asynClient.setMaxRetriesAndTimeout(0, 10000);
                asynClient.addHeader("Connection","Close");
                GsonBuilder gsonBuilder=new GsonBuilder();
                gsonBuilder.serializeNulls();
                final Gson gson = gsonBuilder.create();
               PostData postData=new PostData();
                Debug.d(LOG_TAG, gson.toJson(postData));
                StringEntity entity = null;
                try {
                    entity = new StringEntity(gson.toJson(postData));
                } catch (UnsupportedEncodingException e1) {
                    e1.printStackTrace();
                }             
               entity.setContentType(new BasicHeader(HTTP.CONTENT_TYPE, "application/json"));
               asynClient.post(context,URL, entity,"application/json",new TextHttpResponseHandler() {

                @Override
                public void onFailure(int statusCode,Header[] headers, String responseString,Throwable throwable) {
                     Debug.v(LOG_TAG,"onFailure(): No change in value=" +responseString);

                }

                @Override
                public void onSuccess(int statusCode, Header[] headers, String responseString) {

                ResponseData responseData=gson.fromJson(responseString, ResponseData.class); 
                    Utils.debugResponse(LOG_TAG+"onSuccess",responseString);

                }


//SocketFactory
import cz.msebera.android.httpclient.conn.ssl.BrowserCompatHostnameVerifier;
import cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory;
import cz.msebera.android.httpclient.params.HttpParams;
import android.net.SSLCertificateSocketFactory;

public class SSLSocketFactoryApache  extends SSLSocketFactory {

    private static final String LOG_TAG =Debug.LOG_TAG_+ "SSLSocketFactoryApache";

    final static HostnameVerifier hostnameVerifier = new BrowserCompatHostnameVerifier();

    public SSLSocketFactoryApache(KeyStore truststore) throws NoSuchAlgorithmException,
    KeyManagementException, KeyStoreException, UnrecoverableKeyException {
        super(truststore);
        // TODO Auto-generated constructor stub
    }



    // Plain TCP/IP (layer below TLS)

    @Override
    public Socket createSocket(Socket socket, String host, int port, boolean autoClose)
            throws IOException, UnknownHostException {
        //Debug.d(LOG_TAG, "createSocket called");
        if (autoClose) {
            // we don't need the plainSocket
            //Debug.d(LOG_TAG, "autoclose");
            socket.close();
        }

        // create and connect SSL socket, but don't do hostname/certificate verification yet
        SSLCertificateSocketFactory sslSocketFactory = (SSLCertificateSocketFactory)SSLCertificateSocketFactory.getDefault(0);
        SSLSocket ssl = (SSLSocket)sslSocketFactory.createSocket(InetAddress.getByName(host), port);

        // enable TLSv1.1/1.2 if available
        // (see https://github.com/rfc2822/davdroid/issues/229)
        //ssl.setEnabledProtocols(ssl.getSupportedProtocols());
        ssl.setEnabledProtocols(GetProtocolList(ssl));
        ssl.setEnabledCipherSuites(GetCipherList(ssl));


        /* // set up SNI before the handshake
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            Log.i(TAG, "Setting SNI hostname");
            sslSocketFactory.setHostname(ssl, host);
        } else {
            Log.d(TAG, "No documented SNI support on Android <4.2, trying with reflection");
            try {
                java.lang.reflect.Method setHostnameMethod = ssl.getClass().getMethod("setHostname", String.class);
                setHostnameMethod.invoke(ssl, host);
            } catch (Exception e) {
                Log.w(TAG, "SNI not useable", e);
            }
        }*/

        // verify hostname and certificate
        SSLSession session = ssl.getSession();
        if (!hostnameVerifier.verify(host, session))
            throw new SSLPeerUnverifiedException("Cannot verify hostname: " + host);


        /*   Debug.d(LOG_TAG, "Established " + session.getProtocol() + " connection with " + session.getPeerHost() +
                " using " + session.getCipherSuite());*/

        return ssl;

    }



    @Override
    public boolean isSecure(Socket sock) throws IllegalArgumentException {
        if (sock instanceof SSLSocket)
            return ((SSLSocket)sock).isConnected();
        return false;
    }



    @Override
    public Socket connectSocket(Socket s, String host, int port, InetAddress localAddress, int localPort, HttpParams params) throws IOException {
        return null;
    }

    @Override
    public Socket createSocket() throws IOException {
        return null;
    }


    protected String[] GetProtocolList(SSLSocket socket)
    {
        String[] preferredProtocols = { "TLSv1", "TLSv1.1", "TLSv1.2", "TLSv1.3" };
        String[] availableProtocols = null;
        try
        {
            availableProtocols = socket.getSupportedProtocols();
            Arrays.sort(availableProtocols);
        }
        catch(Exception e)
        {
            return new String[]{ "TLSv1" };
        }

        List<String> aa = new ArrayList<String>();
        for(int i = 0; i < preferredProtocols.length; i++)
        {
            int idx = Arrays.binarySearch(availableProtocols, preferredProtocols[i]);
            if(idx >= 0)
                aa.add(preferredProtocols[i]);
        }

        return aa.toArray(new String[0]);
    }



    protected String[] GetCipherList(SSLSocket socket)
    {
        String[] preferredCiphers = {

                // *_CHACHA20_POLY1305 are 3x to 4x faster than existing cipher suites.
                //   http://googleonlinesecurity.blogspot.com/2014/04/speeding-up-and-strengthening-https.html
                // Use them if available. Normative names can be found at (TLS spec depends on IPSec spec):
                //   http://tools.ietf.org/html/draft-nir-ipsecme-chacha20-poly1305-01
                //   http://tools.ietf.org/html/draft-mavrogiannopoulos-chacha-tls-02
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
                "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_SHA",
                "TLS_ECDHE_RSA_WITH_CHACHA20_SHA",

                "TLS_DHE_RSA_WITH_CHACHA20_POLY1305",
                "TLS_RSA_WITH_CHACHA20_POLY1305",
                "TLS_DHE_RSA_WITH_CHACHA20_SHA",
                "TLS_RSA_WITH_CHACHA20_SHA",

                // Done with bleeding edge, back to TLS v1.2 and below
                "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
                "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
                "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",

                "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384",
                "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256",

                // TLS v1.0 (with some SSLv3 interop)
                "TLS_DHE_RSA_WITH_AES_256_CBC_SHA384",
                "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256",
                "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
                "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",

                "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA",
                "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA",
                "SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA",
                "SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA",

                // RSA key transport sucks, but they are needed as a fallback.
                // For example, microsoft.com fails under all versions of TLS
                // if they are not included. If only TLS 1.0 is available at
                // the client, then google.com will fail too. TLS v1.3 is
                // trying to deprecate them, so it will be interesteng to see
                // what happens.
                "TLS_RSA_WITH_AES_256_CBC_SHA256",
                "TLS_RSA_WITH_AES_256_CBC_SHA",
                "TLS_RSA_WITH_AES_128_CBC_SHA256",
                "TLS_RSA_WITH_AES_128_CBC_SHA"
        };

        String[] availableCiphers = null;

        try
        {
            availableCiphers = socket.getSupportedCipherSuites();
            Arrays.sort(availableCiphers);
        }
        catch(Exception e)
        {
            return new String[] {
                    "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",
                    "TLS_DHE_DSS_WITH_AES_256_CBC_SHA",
                    "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
                    "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
                    "TLS_RSA_WITH_AES_256_CBC_SHA256",
                    "TLS_RSA_WITH_AES_256_CBC_SHA",
                    "TLS_RSA_WITH_AES_128_CBC_SHA256",
                    "TLS_RSA_WITH_AES_128_CBC_SHA",
                    "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
            };
        }

        List<String> aa = new ArrayList<String>();
        for(int i = 0; i < preferredCiphers.length; i++)
        {
            int idx = Arrays.binarySearch(availableCiphers, preferredCiphers[i]);
            if(idx >= 0)
                aa.add(preferredCiphers[i]);
        }

        //aa.add("TLS_EMPTY_RENEGOTIATION_INFO_SCSV");

        return aa.toArray(new String[0]);
    }


}


    }
``````

httpclient-4.4.1.2, android-async-http-1.4.9.jar

**Comment by smarek** [comment]
Thank you for detailed report.

This will be solved in #1029, where I'll concentrace issues about using new underlying HttpClient library and cross-support of SSL/TLS versions vs. Server supported versions
