### ISSUE TITLE
JsonHttpRH: response body is null, calling onFailure(Throwable, JSONObject)

### ISSUE THREAD

**Issue by While1true** [android-async-http/android-async-http#1229]
偶尔会出现这个问题，一直这样。网络是好的，服务器也是有响应的（浏览器测试，其他客户端测试是ok的）。
JsonHttpRH: response body is null, calling onFailure(Throwable, JSONObject)
JsonHttpRH: onFailure(int, Header[], Throwable, JSONObject) was not overriden, but callback was received
                                                              org.apache.http.conn.HttpHostConnectException: Connection to https://api.saibaizi.com refused
                                                                  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:202)
                                                                  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
                                                                  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
                                                                  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
                                                                  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:597)
                                                                  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:517)
                                                                  at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
                                                                  at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
                                                                  at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.net.ConnectException: failed to connect to /121.196.225.194 (port 443) after 10000ms: isConnected failed: ENETUNREACH (Network is unreachable)
                                                                  at libcore.io.IoBridge.isConnected(IoBridge.java:267)
                                                                  at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
                                                                  at libcore.io.IoBridge.connect(IoBridge.java:127)
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:461)
                                                                  at java.net.Socket.connect(Socket.java:918)
                                                                  at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
                                                                  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:163)
                                                                  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164) 
                                                                  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119) 
                                                                  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360) 
                                                                  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:597) 
                                                                  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:517) 
                                                                  at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146) 
                                                                  at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177) 
                                                                  at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106) 
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
                                                               Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
                                                                  at libcore.io.IoBridge.isConnected(IoBridge.java:252)
                                                                  at libcore.io.IoBridge.connectErrno(IoBridge.java:191) 
                                                                  at libcore.io.IoBridge.connect(IoBridge.java:127) 
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188) 
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:461) 
                                                                  at java.net.Socket.connect(Socket.java:918) 
                                                                  at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119) 
                                                                  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:163) 
                                                                  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164) 
                                                                  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119) 
                                                                  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360) 
                                                                  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:597) 
                                                                  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:517) 
                                                                  at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146) 
                                                                  at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177) 
                                                                  at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106) 
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by smarek** [comment]
This is not issue of the library. Seems like backend / access permissions issue
