### ISSUE TITLE
java.io.InterruptedIOException: Connection has been shut down

### ISSUE THREAD

**Issue by poorna204** [android-async-http/android-async-http#1263]
Hi, 

I'm getting the following exception. How can I fix it? Please help me. Thanks. 

Non-fatal Exception: java.io.InterruptedIOException: Connection has been shut down
       at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:579)
       at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
       at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
       at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
       at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
       at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by cz.msebera.android.httpclient.impl.conn.ConnectionShutdownException
       at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.assertValid(AbstractClientConnAdapter.java:155)
       at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.getSSLSession(AbstractClientConnAdapter.java:287)
       at cz.msebera.android.httpclient.impl.client.DefaultUserTokenHandler.getUserToken(DefaultUserTokenHandler.java:80)
       at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:550)
       at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
       at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
       at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
       at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
       at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by smarek** [comment]
Well, find out the cause of the IO interrupt (it is probably device or server side), and/or repeat the request
