### ISSUE TITLE
 javax.net.ssl.SSLException: hostname in certificate didn't match: 

### ISSUE THREAD

**Issue by poorna204** [android-async-http/android-async-http#1264]
Non-fatal Exception: javax.net.ssl.SSLException: hostname in certificate didn't match: <enterprise.work> != <aisf3-ccas01.edmc.edu> OR <aisf3-ccas01.edmc.edu>
       at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:233)
       at cz.msebera.android.httpclient.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
       at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:154)
       at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:135)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:561)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:536)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:472)
       at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
       at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
       at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
       at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
       at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
       at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
       at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
       at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
       at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
       at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
       at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by alexeric** [comment]
I have the same issue

**Comment by leopreuss** [comment]
I have the same issue too . When I go to my web site through a browser via HTTPS the certificate sent is correct, but when I make a connection through AsyncHTTPClient, the certificate is sent not to my specific domain, but to a shared domain (where it is hosted), and that's why this SSLException is thrown. 

I think AsyncHttpClient does not support TLSv1.2 protocol version which is used by the host and instead, another certificate is sent.

**Comment by dsokac** [comment]
Is this issue fixed? I would be thankful if this fix is availble asap.... I got the same issue and I would not like to implement the class with HttpURLConnection because it will cause me to rewrite whole class built with your AsyncHttpClient...

**Comment by xCalifier** [comment]
Same problem and could not even fix this with custom SSLSocketFactory.
This library at its core is using deprecated code, I think its dead now. I will just have to replace 30 functions, 800 lines of code.

**Comment by amiga** [comment]
Still happening! Any fix?

**Comment by xCalifier** [comment]
No, whenever i force https this exception pops out, but only in some
devices, not every devices face this error.

**Comment by amiga** [comment]
I managed to get around it using:
AsyncHttpClient  client = new AsyncHttpClient(true,80,443);

**Comment by xCalifier** [comment]
I can't use fixNoHttpException to true because i am trying to use ssl pinning

**Comment by kaleeswaran14** [comment]
Is this library maintained ? Will I get this issue fixed ?

**Comment by EdwardQuixote** [comment]
I have the same problem.
I'm calling a Google Firebase Cloud Functions end-point with this library, but I hit this problem.
However, using Volley has helped me so far even though I'm looking for another solution.
This library is great! GREAT! But I've noticed it's not being well maintained, that's why I've decided to switch to Volley in the meantime.

**Comment by smarek** [comment]
SNI support will be solved in #991 . Closing this issue as duplicate
