### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks

### ISSUE THREAD

**Issue by cotfas** [android-async-http/android-async-http#1268]
```
09-07 20:29:25.790 29598-29607/***** E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                           java.lang.Throwable: Explicit termination method 'close' not called
                                                               at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                               at com.android.org.conscrypt.Platform.closeGuardOpen(Platform.java:282)
                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:316)
                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
                                                               at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
                                                               at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.<init>(SocketInputBuffer.java:79)
                                                               at cz.msebera.android.httpclient.impl.SocketHttpClientConnection.createSessionInputBuffer(SocketHttpClientConnection.java:97)
                                                               at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.createSessionInputBuffer(DefaultClientConnection.java:188)
                                                               at cz.msebera.android.httpclient.impl.SocketHttpClientConnection.bind(SocketHttpClientConnection.java:149)
                                                               at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.update(DefaultClientConnection.java:243)
                                                               at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:219)
                                                               at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.layerProtocol(AbstractPoolEntry.java:243)
                                                               at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.layerProtocol(AbstractPooledConnAdapter.java:152)
                                                               at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:814)
                                                               at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:615)
                                                               at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
                                                               at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
                                                               at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
                                                               at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
                                                               at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
                                                               at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                               at java.lang.Thread.run(Thread.java:761)
09-07 20:29:25.792 29598-29607/*** E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                           java.lang.Throwable: Explicit termination method 'close' not called
                                                               at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                               at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
                                                               at java.net.Socket.createImpl(Socket.java:451)
                                                               at java.net.Socket.getImpl(Socket.java:517)
                                                               at java.net.Socket.setSoTimeout(Socket.java:1108)
                                                               at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:116)
                                                               at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
                                                               at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
                                                               at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
                                                               at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
                                                               at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
                                                               at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
                                                               at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
                                                               at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
                                                               at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
                                                               at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
                                                               at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
                                                               at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                               at java.lang.Thread.run(Thread.java:761)
```

**Comment by smarek** [comment]
Tackling StrictMode is real challenge, this might be addressed in 1.5.x, however no soon I presume
