### ISSUE TITLE
ClientProtocolException when upload file[issue]

### ISSUE THREAD

**Issue by weeklynote** [android-async-http/android-async-http#1273]
```
W/System.err: cz.msebera.android.httpclient.client.ClientProtocolException
W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:776)
W/System.err: Caused by: cz.msebera.android.httpclient.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity.  The cause lists the reason the original request failed.
W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:659)
W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
W/System.err: 	... 9 more
W/System.err: Caused by: java.net.SocketException: Connection reset
W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
W/System.err:     at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:181)
W/System.err:     at cz.msebera.android.httpclient.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:115)
W/System.err:     at com.loopj.android.http.SimpleMultipartEntity$FilePart.writeTo(SimpleMultipartEntity.java:288)
W/System.err:     at com.loopj.android.http.SimpleMultipartEntity.writeTo(SimpleMultipartEntity.java:219)
W/System.err:     at cz.msebera.android.httpclient.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
W/System.err:     at cz.msebera.android.httpclient.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
W/System.err:     at cz.msebera.android.httpclient.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:231)
W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
W/System.err: 	... 11 more
```

**Comment by smarek** [comment]
Well read the stacktrace, `Cannot retry request with a non-repeatable request entity.  The cause lists the reason the original request failed.` is pretty explanatory
