### ISSUE TITLE
OutOfMemoryError and  ArrayIndexOutOfBoundsException occurred when I create AsyncHttpClient

### ISSUE THREAD

**Issue by oopdual** [android-async-http/android-async-http#1292]
I'm using android-async-http in my app and it works well past 2 years.
However, I've got crash report from fabric and they were so weird to understand for me.
My code is below.

**AsyncHttpClient client = new AsyncHttpClient();**

and my crash reports are two kinds and they are below.

1. OutOfMemory
Fatal Exception: java.lang.OutOfMemoryError: java.lang.String[] of length 1464720139 would overflow
       at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.(AbstractVerifier.java:75)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.(SSLSocketFactory.java:145)
       at com.loopj.android.http.AsyncHttpClient.getDefaultSchemeRegistry(AsyncHttpClient.java:301)
       at com.loopj.android.http.AsyncHttpClient.(AsyncHttpClient.java:177)
       at com.loopj.android.http.AsyncHttpClient.(AsyncHttpClient.java:147)

2. ArrayIndexOutOfRange
Caused by java.lang.ArrayIndexOutOfBoundsException: length=14; index=-711987539
       at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.(AbstractVerifier.java:75)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.(SSLSocketFactory.java:145)
       at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.getSocketFactory(SSLSocketFactory.java:162)
       at com.loopj.android.http.AsyncHttpClient.getDefaultSchemeRegistry(AsyncHttpClient.java:301)
       at com.loopj.android.http.AsyncHttpClient.(AsyncHttpClient.java:177)
       at com.loopj.android.http.AsyncHttpClient.(AsyncHttpClient.java:147)

How could it happen? Is there someone who see this kind of error?
Or Is there something that can be explained that problems?

Someone please let me know.

**Comment by StreethawkNick** [comment]
This issue seems to be when you are passing a very large String[] value to the HTTPClient . Did you check the String you are passing to the HTTP call?

**Comment by oopdual** [comment]
@StreethawkNick At that time, we didn't send or receive any packet, just create a instance of AsyncHttpClient. And the code occurred the errors is below

/**
     * This contains a list of 2nd-level domains that aren't allowed to
     * have wildcards when combined with country-codes.
     * For example: [*.co.uk].
     * <p/>
     * The [*.co.uk] problem is an interesting one.  Should we just hope
     * that CA's would never foolishly allow such a certificate to happen?
     * Looks like we're the only implementation guarding against this.
     * Firefox, Curl, Sun Java 1.4, 5, 6 don't bother with this check.
     */
    private final static String[] BAD_COUNTRY_2LDS =
          { "ac", "co", "com", "ed", "edu", "go", "gouv", "gov", "info",
            "lg", "ne", "net", "or", "org" };

actually I can't understand how could make the error that code.

**Comment by harleyknd1** [comment]
Can you share the full code you wrote when creating the client, and maybe the code calling the creation of the client?

Creating and destroying Async clients repeatedly in a short span of time can result in an overflow,
Though this error looks more to do with SSL

**Comment by ali-augmedix** [comment]
Try to change your AsyncHttpClient to SyncHttpClient.
from **new AsyncHttpClient()** to **new SyncHttpClient()**

Its solved the OOM issue for my case

**Comment by smarek** [comment]
1st issue might be upstream issue of HttpClient AbstractVerifier.java, and you didn't list what version of library you do use, so I'm unable to help you

2nd issue looks the same.

However both issues look like HttpClient is failing due to information listed in SSL Certificate the server provides, or in the SSL Certificate you've provided to do certificate pinning
