### ISSUE TITLE
android User-space exception detected! java.lang.NullPointerException

### ISSUE THREAD

**Issue by JuanAsd** [android-async-http/android-async-http#1293]
I'm getting this problem here: creating the ResultadoObject it goes to the catch.

```
str = "", responseBody = {byte[0]@5870}, while the statusCode: 200
```
I guess I'm receiving an empty responseBody, any help please? Thank you
```
client.post(url, requestParams, new AsyncHttpResponseHandler(){
  @Override
  public void onSuccess(int statusCode, Header[] headers, byte[] **responseBody**) {
      System.out.println("onSuccess");
      String str = null;
      try {
          str = new String(responseBody, "UTF-8");
      }
      catch (UnsupportedEncodingException e) {
          e.printStackTrace();
      }
      if (str != null)
      {
          ResultadoObject resultado = null;
          try {
             **resultado = new ResultadoObject(new JSONObject(str));**
          } catch (JSONException e) {
             e.printStackTrace();
          }
          if (resultado.Flag != 0 && resultado.IDMantenimiento != 0)
          {
             loading = false;
             progressDialog.dismiss();
             cambios = true;
             getMantenimiento(resultado.IDMantenimiento);
          }
```

```
**User-space exception detected!**
java.lang.NullPointerException: Attempt to read from field 'int com.model.ResultadoObject.Flag' on a null object reference at com.activities.MantenimientoEditarActivity$7.onSuccess(MantenimientoEditarActivity.java:791) at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351) at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6541) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by harleyknd1** [comment]
`java.lang.NullPointerException: Attempt to read from field 'int com.model.ResultadoObject.Flag' on a null `

your flag is Null when going into the check
`if (resultado.Flag != 0 && resultado.IDMantenimiento != 0)`

that's the portion is erroring on cause resultado.Flag == null

to fix it you can write
`if(resultado.Flag != null && resultado.Flag != 0 && resultado.IDMantenimiento != null && IDMantenimiento != 0)`

**Comment by smarek** [comment]
This is not issue of the library
