### ISSUE TITLE
Seems that SyncHttpClient is not sync now

### ISSUE THREAD

**Issue by likman** [android-async-http/android-async-http#1324]
Hello. 
I use SyncHttpClient that called in AsyncTask in my project. After updating to 1.4.10 version, my program started crashing on POST requests.

Error from logcat:

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: ru.nsteam.nsteamreports, PID: 7503
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.AssertionError: use looper thread, must call Looper.prepare() first!
        at com.loopj.android.http.Utils.asserts(Utils.java:39)
        at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:137)
        at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:122)
        at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:110)
        at com.loopj.android.http.TextHttpResponseHandler.<init>(TextHttpResponseHandler.java:73)
        at com.loopj.android.http.JsonHttpResponseHandler.<init>(JsonHttpResponseHandler.java:48)
```

**Comment by saeed-rz** [comment]
in logcat :
> Caused by: java.lang.AssertionError: use looper thread, must call Looper.prepare() first!

please use `Looper.prepare();` before client.post or any HTTP method interface.

for more info check this [comment](https://github.com/android-async-http/android-async-http/issues/1325#issuecomment-545919846)

Let me know if that works for you

**Comment by smarek** [comment]
Also @likman @nextflex could you try on your target device run the latest sample application, specifically "Synchronous GET request" and "IntentService Synchronised Request" both use SyncHttpClient, and in my dev/test environment those work properly, so I don't suspect the library to be broken.
