### ISSUE TITLE
SocketTimeout with Samsung XCover

### ISSUE THREAD

**Issue by Asleif** [android-async-http/android-async-http#1328]
Hi,

I have a strange issue, that is leaving me exasperated. I am using android async to post an image to our server. It works with every imaginable device I have tested it, the only specific combination in which I get a SocketTimeout is with a specific provider (A1) and the Samsung XCover S4. Unfortunately this is the exact usecase our customer wants.

I am getting this error. In any other combination (other Provider, same phone, same provider, other phone) it works perfectly.

`2019-12-12 11:52:09.411 16086-16789/com.example.callcenter.rema W/System.err: java.net.SocketTimeoutException: Read timed out
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:176)
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:144)
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
2019-12-12 11:52:09.412 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
2019-12-12 11:52:09.413 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-12 11:52:09.414 16086-16789/com.example.callcenter.rema W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-12-12 11:52:09.415 16086-16789/com.example.callcenter.rema W/System.err: java.net.SocketTimeoutException: Read timed out`

**Comment by saeed-rz** [comment]
what is the android version of this phone "Samsung XCover S4"?
