### ISSUE TITLE
E/AsyncHttpRH: User-space exception detected! in App Bundle Only

### ISSUE THREAD

**Issue by caevan** [android-async-http/android-async-http#1329]
I am having an issue where if I deploy my app using the android-async-http library as an apk. The app works perfectly.
If I then deploy the App as a bundle through Google Play for testing I get the following error
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at au.com.traveldaily.pharmacydaily.b.a(Unknown Source:11)
        at au.com.traveldaily.pharmacydaily.f.d$a.onSuccess(Unknown Source:69)
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(Unknown Source:164)
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(Unknown Source:2)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884) 
I am using version 1.4.10 is there something I need to do differently when deploying as a Bundle.

**Comment by smarek** [comment]
Well since the issue raises from your code (second level, Unknown Source:11) I'd guess there is some discrepancy between your testing and production environment, and you did not validate the data correctly, before passing to "au.com.traveldaily.pharmacydaily.b.a" 
Putting up "on hold" for this issue, if you don't provide more info from debugging in 2 weeks, this ticket will be closed.

**Comment by caevan** [comment]
Thank you for your help. 
The issue was in how the build was created, it is now resolved
