### ISSUE TITLE
SocketTimeoutException or ConnectTimeOutException When making api call Using AsyncHttpClient after 10 minutes

### ISSUE THREAD

**Issue by nitinjain92** [android-async-http/android-async-http#1339]
Hi,

I am getting SocketTimeoutException or ConnectTimeOutException When making api call Using AsyncHttpClient after 10 minutes.

Preconditions :
1. I am using AsyncHttpClient API version 1.4.9
2. I have created singleton instance of AsyncHttpClient as per documentation

Reporduction steps:-
1. In my Android app I fetch data via an API call using AsyncHttpClient API
2. Now I do not leave from that screen and just lock my mobile for more than 10 minutes.
3. After 10 minutes I again refresh same page using AsyncHttpClient API, this time below exception occurs.

Can you help me in this issue?

2020-06-18 13:26:11.260 10476-24630/? W/System.err: java.net.SocketTimeoutException: failed to connect to www.mylinq.in/64:ff9b::d7e:f08d (port 443) from /2409:4052:617:2184::26c6:78ac (port 44090) after 20000ms
2020-06-18 13:26:11.269 10476-24630/? W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
2020-06-18 13:26:11.269 10476-24630/? W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:135)
2020-06-18 13:26:11.269 10476-24630/? W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2020-06-18 13:26:11.269 10476-24630/? W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2020-06-18 13:26:11.269 10476-24630/? W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2020-06-18 13:26:11.269 10476-24630/? W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2020-06-18 13:26:11.270 10476-24630/? W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2020-06-18 13:26:11.270 10476-24630/? W/System.err:     at java.net.Socket.connect(Socket.java:621)
2020-06-18 13:26:11.270 10476-24630/? W/System.err:     at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
2020-06-18 13:26:11.271 10476-24630/? W/System.err:     at cz.msebera.android.httpclient.conn.ssl.f.a(SSLSocketFactory.java:31)
2020-06-18 13:26:11.271 10476-24630/? W/System.err:     at cz.msebera.android.httpclient.conn.ssl.f.a(SSLSocketFactory.java:11)
2020-06-18 13:26:11.271 10476-24630/? W/System.err:     at cz.msebera.android.httpclient.conn.ssl.f.a(SSLSocketFactory.java:23)
2020-06-18 13:26:11.272 10476-24630/? W/System.err:     at cz.msebera.android.httpclient.conn.s.k.a(SchemeSocketFactoryAdaptor.java:5)
2020-06-18 13:26:11.272 10476-24630/? W/System.err:     at cz.msebera.android.httpclient.impl.conn.f.a(DefaultClientConnectionOperator.java:22)

**Comment by saeed-rz** [comment]
hi @nitinjain92 
can you show me the implementation of AsyncHttpClient and how you call it from your activity/fragment?
I have tested our sample code and no errors occur

**Comment by saeed-rz** [comment]
and try to use the latest version, 1.4.10
