### ISSUE TITLE
[Issue] Use looper thread, must call Looper.prepare error v1.4.11

### ISSUE THREAD

**Issue by dss-kenya** [android-async-http/android-async-http#1391]
I tried upgrading from v1.4.9 to v1.4.11 and i have a class that extends JsonHttpResponseHandler, however, the code now crashes with the following error:

```
java.lang.AssertionError: use looper thread, must call Looper.prepare() first!
    at com.loopj.android.http.Utils.asserts(Utils.java:39)
    at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:137)
    at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:122)
    at com.loopj.android.http.AsyncHttpResponseHandler.<init>(AsyncHttpResponseHandler.java:110)
    at com.loopj.android.http.TextHttpResponseHandler.<init>(TextHttpResponseHandler.java:73)
    at com.loopj.android.http.JsonHttpResponseHandler.<init>(JsonHttpResponseHandler.java:48)
```

I also see that in the code we have the following in the sdk:

```
public AsyncHttpResponseHandler(boolean usePoolThread) {
        this(usePoolThread ? null : Looper.myLooper(), usePoolThread);
    }
```

Is therefore something that is missed? and Looper.prepare has to be called in the sdk? Or how do we handle this?
also, this crash does not seem to happen on version 1.4.9.

**Comment by Spraynard** [comment]
I also experienced this issue when using a general `AsyncHttpResponseHandler()` call in my `client.post()` method with `v1.4.11`.

<img width="761" height="58" alt="Image" src="https://github.com/user-attachments/assets/e4b0e897-01c0-4470-80b5-5c339e4a18bf" />

Instead of upgrading to `v1.4.11` I upgraded to `v1.4.9` and the issue went away

Here is a stack trace and message that I got

<img width="1079" height="388" alt="Image" src="https://github.com/user-attachments/assets/85677082-55d6-4c0a-a05e-d42d6013f847" />
