### ISSUE TITLE
ConnectTimeoutException broken in failure respond

### ISSUE THREAD

**Issue by alex-kor** [android-async-http/android-async-http#361]
I have an issue with ConnectionTimeoutExeption in a latest release. It was fixed before and now is broken again.

I did set a timeout to very short to be able to test connection timeout and I don't have a respond in my onFailure method.

```
@Override
public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
          Log.e("HTTP CLIENT","Error code: "+statusCode+" content: "+new String(responseBody));

    if ( error.getCause() instanceof ConnectTimeoutException )
    {
            Log.e("HTTP CLIENT","Connection timeout !");
    }
    super.onFailure(statusCode, headers, responseBody, error);
}
```

Could you please check if something wrong.

This is an exception what I've got:

```
org.apache.http.conn.ConnectTimeoutException: Connect to /50.16.223.98:80 timed out
10-24 13:48:46.693: W/System.err(5220):     at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
10-24 13:48:46.693: W/System.err(5220):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
10-24 13:48:46.696: W/System.err(5220):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
10-24 13:48:46.700: W/System.err(5220):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
10-24 13:48:46.704: W/System.err(5220):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
10-24 13:48:46.716: W/System.err(5220):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
10-24 13:48:46.716: W/System.err(5220):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
10-24 13:48:46.720: W/System.err(5220):     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:72)
10-24 13:48:46.728: W/System.err(5220):     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:90)
10-24 13:48:46.732: W/System.err(5220):     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:52)
10-24 13:48:46.732: W/System.err(5220):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
10-24 13:48:46.736: W/System.err(5220):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-24 13:48:46.736: W/System.err(5220):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-24 13:48:46.736: W/System.err(5220):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-24 13:48:46.736: W/System.err(5220):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-24 13:48:46.736: W/System.err(5220):     at java.lang.Thread.run(Thread.java:856)
```

**Comment by Lengends** [comment]
这个问题最终有解决的办法吗

**Comment by NortonAhu** [comment]
我最近项目也遇到这个问题 80 端口连接超时。我怀疑是不是多个 AsyncHttpClient 之间影响的，第一个client 使用80端口 如果还没结束 其他client 会受到影响。

**Comment by smarek** [comment]
Only English please
