### ISSUE TITLE
org.apache.http.NoHttpResponseException: The target server failed to respond

### ISSUE THREAD

**Issue by niteshgoel** [android-async-http/android-async-http#363]
```
I am getting this error message in response to a post request.

10-26 19:31:14.063: W/System.err(4839): org.apache.http.NoHttpResponseException: The target server failed to respond
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:179)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:421)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
10-26 19:31:14.083: W/System.err(4839):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
10-26 19:31:14.083: W/System.err(4839):     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:78)
10-26 19:31:14.083: W/System.err(4839):     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:102)
10-26 19:31:14.083: W/System.err(4839):     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:58)
10-26 19:31:14.083: W/System.err(4839):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
10-26 19:31:14.083: W/System.err(4839):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
10-26 19:31:14.083: W/System.err(4839):     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
10-26 19:31:14.083: W/System.err(4839):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
10-26 19:31:14.083: W/System.err(4839):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
10-26 19:31:14.083: W/System.err(4839):     at java.lang.Thread.run(Thread.java:1019)
10-26 19:31:14.093: W/System.err(4839): org.apache.http.NoHttpResponseException: The target server failed to respond
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:179)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:421)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
10-26 19:31:14.093: W/System.err(4839):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
10-26 19:31:14.093: W/System.err(4839):     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:78)
10-26 19:31:14.093: W/System.err(4839):     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:102)
10-26 19:31:14.093: W/System.err(4839):     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:58)
10-26 19:31:14.093: W/System.err(4839):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
10-26 19:31:14.093: W/System.err(4839):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
10-26 19:31:14.093: W/System.err(4839):     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
10-26 19:31:14.093: W/System.err(4839):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
10-26 19:31:14.093: W/System.err(4839):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
10-26 19:31:14.093: W/System.err(4839):     at java.lang.Thread.run(Thread.java:1019)
```

**Comment by twjitm** [comment]
I have this problem, too
