### ISSUE TITLE
ConcurrentModificationException on AsyncHttpClient.cancelRequests

### ISSUE THREAD

**Issue by TheLittleBoy** [android-async-http/android-async-http#632]
I just very fast request and cancelRequests. you can get an exception like this:

```
E/AndroidRuntime(11529): FATAL EXCEPTION: Thread-8007
E/AndroidRuntime(11529): java.util.ConcurrentModificationException
E/AndroidRuntime(11529): at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
E/AndroidRuntime(11529): at com.loopj.android.http.AsyncHttpClient$4.run(AsyncHttpClient.java:647)
E/AndroidRuntime(11529): at java.lang.Thread.run(Thread.java:856)
```

can you help me?

**Comment by mbmc** [comment]
It's still happening using 1.4.6
```
 java.util.ConcurrentModificationException
 	at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
 	at com.loopj.android.http.AsyncHttpClient$4.run(AsyncHttpClient.java:716)
 	at java.lang.Thread.run(Thread.java:841)
```
I invoke cancel, sendRequest, cancel, sendRequest successively (to handle a search in the toolbar), then it crashes.

**Comment by guhongjie** [comment]
It's still happening using 1.4.8
                                                                java.util.ConcurrentModificationException
                                                                    at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
                                                                    at com.loopj.android.http.AsyncHttpClient.sendRequest(AsyncHttpClient.java:1403)
                                                                    at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:1043)
                                                                    at com.inke.common.api.ApiManager.request(ApiManager.java:126)
                                                                    at com.inke.infan.apis.ApisInjectHelper.request(ApisInjectHelper.java:240)
                                                                    at com.inke.infan.apis.ApisInjectHelper.cacheRequest(ApisInjectHelper.java:223)
                                                                    at com.inke.infan.apis.ApisInjectHelper$1.onRun(ApisInjectHelper.java:199)
                                                                    at com.inke.common.stack_obj.StackRunnable.run(StackRunnable.java:21)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:818)
