### ISSUE TITLE
NoHttpResponseException 1.4.6

### ISSUE THREAD

**Issue by valeriologiudice** [android-async-http/android-async-http#747]
Hello, I'm having a serious problem connecting with my server. The app doesn't connect and I have se following output with several Retry request attempts. I'm using 1.4.6 and I followed your sample codes. I'm sure that the server is online. If I connect from my iOS version of the app it works. What can I do? Best regards.

```
11-27 19:43:41.952: W/System.err(8669): org.apache.http.NoHttpResponseException: The target server failed to respond
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
11-27 19:43:41.962: W/System.err(8669):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
11-27 19:43:41.962: W/System.err(8669):     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
11-27 19:43:41.962: W/System.err(8669):     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
11-27 19:43:41.962: W/System.err(8669):     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
11-27 19:43:41.962: W/System.err(8669):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-27 19:43:41.962: W/System.err(8669):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-27 19:43:41.962: W/System.err(8669):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-27 19:43:41.962: W/System.err(8669):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-27 19:43:41.962: W/System.err(8669):     at java.lang.Thread.run(Thread.java:841)
11-27 19:43:43.483: D/AsyncHttpResponseHandler(8669): Request retry no. 1
```

**Comment by valeriologiudice** [comment]
@smarek Hi I still have this problem. I have found no solution. Any suggestion?
